/**
 * Email sending module.
 * Prefers SMTP via Nodemailer using SMTP_* envs.
 * If SENDGRID_API_KEY is set, uses SendGrid Web API.
 * If RESEND_API_KEY is set (and no SendGrid), uses Resend Web API.
 */

import nodemailer from 'nodemailer';
import { logger } from './logger.js';
import fetch from 'node-fetch';

/**
 * PUBLIC_INTERFACE
 * sendContactEmail(payload, req)
 * Sends email with the contact form data using configured transport.
 * - payload: { name, email, message }
 * Returns provider response metadata including messageId if available.
 */
export async function sendContactEmail(payload, req) {
  const useSendgrid = !!process.env.SENDGRID_API_KEY;
  const useResend = !useSendgrid && !!process.env.RESEND_API_KEY;

  if (useSendgrid) {
    return sendWithSendgrid(payload);
  }
  if (useResend) {
    return sendWithResend(payload);
  }
  return sendWithSmtp(payload, req);
}

function renderSubject(name) {
  const n = String(name || 'Visitor').slice(0, 120);
  return `New portfolio contact from ${n}`;
}

function renderText({ name, email, message }) {
  return [
    `You have a new contact submission from your portfolio website.`,
    ``,
    `Name: ${name}`,
    `Email: ${email}`,
    ``,
    `Message:`,
    `${message}`,
    ``,
    `--`,
    `This email was generated by backend_contact service.`,
  ].join('\n');
}

function renderHtml({ name, email, message }) {
  const escape = (s) => String(s || '').replace(/[&<>"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]));
  return `
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
    <h2>New portfolio contact</h2>
    <p><strong>Name:</strong> ${escape(name)}</p>
    <p><strong>Email:</strong> ${escape(email)}</p>
    <p><strong>Message:</strong></p>
    <pre style="white-space:pre-wrap; background:#f7f7f7; padding:12px; border-radius:8px;">${escape(message)}</pre>
    <hr/>
    <small>backend_contact service</small>
  </div>`;
}

async function sendWithSmtp(payload, req) {
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || 587);
  const secure = String(process.env.SMTP_SECURE || 'false') === 'true';
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  const from = process.env.SMTP_FROM || 'Portfolio Contact <no-reply@example.com>';
  const to = process.env.SMTP_TO || process.env.RESEND_TO || process.env.SENDGRID_TO || 'you@example.com';

  if (!host || !user || !pass) {
    logger.warn('SMTP not fully configured; simulating success');
    return { id: null, simulated: true };
  }

  const transporter = nodemailer.createTransport({
    host, port, secure,
    auth: { user, pass }
  });

  const mail = {
    from,
    to,
    subject: renderSubject(payload.name),
    text: renderText(payload),
    html: renderHtml(payload),
    headers: {
      'X-Contact-Client-IP': req?.ip || '',
      'X-Contact-User-Agent': req?.get?.('user-agent') || ''
    }
  };

  const info = await transporter.sendMail(mail);
  logger.info('SMTP mail sent', { messageId: info.messageId });
  return { messageId: info.messageId, provider: 'smtp' };
}

async function sendWithSendgrid(payload) {
  const apiKey = process.env.SENDGRID_API_KEY;
  const from = process.env.SENDGRID_FROM || process.env.SMTP_FROM || 'Portfolio Contact <no-reply@example.com>';
  const to = process.env.SENDGRID_TO || process.env.SMTP_TO || 'you@example.com';

  if (!apiKey) {
    logger.warn('SENDGRID_API_KEY missing; fallback simulate');
    return { id: null, simulated: true };
  }

  const body = {
    personalizations: [{ to: [{ email: to }] }],
    from: parseFromAddress(from),
    subject: renderSubject(payload.name),
    content: [
      { type: 'text/plain', value: renderText(payload) },
      { type: 'text/html', value: renderHtml(payload) }
    ]
  };

  const resp = await fetch('https://api.sendgrid.com/v3/mail/send', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });

  if (!resp.ok) {
    const t = await resp.text();
    logger.error('SendGrid send failed', { status: resp.status, body: t });
    throw new Error('sendgrid_failed');
  }
  const id = resp.headers.get('x-message-id') || null;
  logger.info('SendGrid mail accepted', { id });
  return { id, provider: 'sendgrid' };
}

async function sendWithResend(payload) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = (process.env.RESEND_FROM || process.env.SMTP_FROM || 'no-reply@example.com').replace(/"/g, '');
  const to = (process.env.RESEND_TO || process.env.SMTP_TO || 'you@example.com').replace(/"/g, '');

  if (!apiKey) {
    logger.warn('RESEND_API_KEY missing; fallback simulate');
    return { id: null, simulated: true };
  }

  const body = {
    from,
    to,
    subject: renderSubject(payload.name),
    html: renderHtml(payload),
    text: renderText(payload)
  };

  const resp = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });

  const data = await resp.json().catch(() => ({}));
  if (!resp.ok) {
    logger.error('Resend send failed', { status: resp.status, body: data });
    throw new Error('resend_failed');
  }

  const id = data.id || null;
  logger.info('Resend mail accepted', { id });
  return { id, provider: 'resend' };
}

function parseFromAddress(from) {
  // handle "Name <email@domain>"
  const m = String(from).match(/^(.*)<([^>]+)>$/);
  if (m) {
    return { email: m[2].trim(), name: m[1].trim().replace(/^"|"$/g, '') };
  }
  return { email: String(from).trim() };
}
